version: '3.8'

services:
  docker-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: houssemino
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql



  discovery-service:
    container_name: discovery-service
    build: ./eureka
    #image: "eureka"
    restart: on-failure
    ports:
      - "8090:8090"
    hostname: eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8090/eureka/
    networks:
      - app-network
    depends_on:
      - docker-mysql

  api-gateway:
    restart: on-failure
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8099:8099"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8090/eureka/
    networks:
      - app-network
    depends_on:
      - discovery-service

  microservice-quiz:
    restart: on-failure
    container_name: microservice-quiz
    build: ./microservice-quiz
    ports:
      - "8092:8092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8090/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/Quiz?autoReconnect=true&useSSL=false
    networks:
      - app-network
    depends_on:
      - discovery-service
      - docker-mysql

networks:
  app-network:
    driver: bridge


volumes:
  db: