version: '3'

services:
  discovery-server:
    build: ./eureka
    ports:
      - "8090:8090"
    restart: always
    networks:
      - app-network
    environment:
      - EUREKA_SERVER=http://discovery-server:8090/eureka/

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8099:8099"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8090/eureka/
    depends_on:
      - discovery-server
    networks:
      - app-network

  python-microservice:
    build: ./news
    volumes:
      - ./news:/usr/src/app
    ports:
      - "5001:80"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8090/eureka/
    networks:
      - app-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"
      - "--http-port=8080"
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data


  microservice-quiz:
    restart: on-failure
    container_name: microservice-quiz
    build: ./microservice-quiz
    ports:
      - "8092:8092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8090/eureka/
    networks:
      - app-network
    depends_on:
      - discovery-server
    volumes:
      - quiz-db-data:/app/Database/Data

  microservice-inscriptions:
    restart: on-failure
    container_name: microservice-inscriptions
    build: ./microservice-inscriptions
    ports:
      - "8093:8093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8090/eureka/
    networks:
      - app-network
    depends_on:
      - discovery-server
    volumes:
      - inscription-db-data:/app/Database/Data


  website-angular:
    build: ./angular-18
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  quiz-db-data: 
    driver: local
  inscription-db-data: 
    driver: local
  keycloak_data:
    driver: local
