spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9009/realms/JobBoardKeyclock

server:
  port: 8099

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka